new change

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,9 +39,9 @@ jobs:
           git log -1 --oneline
 
       - name: Verify PM2 status
-        run:
-          pm2 status
-          if pm2 list | grep -qE "errored|stopped"; then
-            echo "one or more processes has errored or stopped"
-            exit 1
-          fi
+        run: |
+            pm2 status
+            if pm2 list | grep -qE "errored|stopped"; then
+              echo "one or more processes has errored or stopped"
+              exit 1
+            fi
